name: registration-page
on:
  push:
    branches:
      - main
      - dev
      - master
    paths-ignore: 
      - frontend/*
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch: 
jobs:
  git-checkout:
    runs-on: self-hosted
    steps:
      - name: cloning-repo
        uses: actions/checkout@v7
      - name: changing-directory
        working-directory: ./backend
        run: mvn clean package
  running-project:
    runs-on: self-hosted
    needs: git-checkout
    steps:
      - name: runningg
        run: java -jar ./target/*.jar
