name: registration-page
on:
  push:
    branches:
      - main
      - dev
      - master
    paths-ignore: 
      - frontend/*
      - .github/*
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch: 
env:
   DB_HOST: ${{ secrets.DB_HOST }}
   DB_NAME: ${{ secrets.DB_NAME }}
   DB_USER: ${{ secrets.DB_USER }}
   DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
jobs:
  java-installation:
    runs-on: self-hosted
    steps:      
      - name: Set up Maven and Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: java --version
  compiling-and-buildig:
    runs-on: self-hosted
    needs: java-installation
    steps:   
      - name: git checkout
        uses: actions/checkout@v7
      - name: maven installation
        uses: s4u/setup-maven-action@3.9.8
        with:
          java-version: 8       
      - name: changing-directory
        working-directory: ./backend
        run: mvn clean package
  running-project:
    runs-on: self-hosted
    needs: compiling-and-buildig
    steps:
      - name: runningg
        run: java -jar ./target/*.jar
