name: registration-page
on:
  push:
    branches:
      - main
      - dev
    paths-ignore: 
      - .github/workflows/*
  pull_request: 
    branches: 
      - main
    types: 
      - closed
  
jobs:
  git-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v7        
      - name: dependencies-install
        working-directory: ./backend
        run: mvn clean package
  building-and-running-application:
    runs-on: ubuntu-latest
    needs: git-checkout
    steps:
      - name: running application
        run: java -jar ./target/*.jar
  running-front-end:
    runs-on: ubuntu-latest
    needs: building-and-running-application
    steps:
      - name: installing dependencies
        run: npm install
        
        
      
